In [56]:
!pip install names
import names
import numpy

Requirement already satisfied (use --upgrade to upgrade): names in ./anaconda3/lib/python3.4/site-packages

In [252]:
num_applicants = 300

# uses numpy.random.choice to weight each category
# _categories and _probability can be modified and extended, but each array must be of equal length
# contains missing values, because we expect those in source data

gender_categories = ['male','female','other','']
gender_probability = [.48,.48,.03,.01]

career_categories = ['grad-student','junior-faculty','senior-faculty','']
career_probability = [.33,.33,.33,.01]

country_categories = ['OECD','non-OECD',''] # see http://www.oecd.org/about/membersandpartners/
country_probability = [.49,.49,.02]

subfield_categories = ['solar','cosmology','astrophysics','exoplanets','']
subfield_probability = [.24,.24,.24,.24,.04]

first_time_categories = ['first_time','returning','']
first_time_probability = [.49,.49,.02]

In [253]:
gender_array = numpy.random.choice(gender_categories, p=gender_probability,size=num_applicants,replace=True)
name_array = [names.get_full_name(gender=i) for i in gender_array]
career_stage_array = numpy.random.choice(career_categories, p=career_probability,size=num_applicants,replace=True)
country_array = numpy.random.choice(country_categories, p=country_probability,size=num_applicants,replace=True)
subfield_array = numpy.random.choice(subfield_categories, p=subfield_probability,size=num_applicants,replace=True)
first_time_array = numpy.random.choice(first_time_categories,p=first_time_probability,size=num_applicants,replace=True)

In [254]:
gender_array

array(['female', 'female', 'male', 'male', 'female', 'female', 'other',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'male', 'female', 'female', 'female', 'male', 'female',
       'female', 'male', 'male', 'female', 'male', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'female', 'male',
       'female', 'male', 'female', 'female', 'male', 'female', 'female',
       'female', 'female', 'female', 'female', 'female', 'female',
       'female', 'male', 'female', 'female', 'male', 'male', 'female',
       'female', '', 'female', 'female', 'female', 'male', 'female',
       'male', 'male', 'female', 'male', 'female', 'female', 'other',
       'male', 'male', 'female', 'male', 'male', '', 'male', 'female',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'female',
       'other', '', 'female', 'male', 'male', 'female', 'female', 'male',
       'male', 'female', 'female', 'male', 'female', 'female', 'female',
       '', 'female', 'female', 'male', 'female', '', 'female', 'female',
       'female', 'male', 'female', 'female', 'female', 'female', 'other',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'male', 'male', 'female', 'female',
       'female', 'female', 'male', 'other', 'female', 'male', 'male',
       'male', 'female', 'male', 'male', 'female', 'male', 'male',
       'female', 'female', 'female', 'female', 'female', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'male', 'male',
       'female', 'female', 'female', 'male', 'other', 'female', 'male',
       'female', 'female', 'female', 'female', 'other', 'female', 'male',
       'female', 'female', 'male', 'male', 'female', 'male', 'female',
       'male', 'male', 'male', 'male', 'male', 'female', 'male', 'male',
       'male', 'female', 'female', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'female', 'female', 'female', 'male', 'female',
       'female', 'male', 'female', 'male', 'male', 'male', 'female',
       'male', 'male', 'male', 'male', 'female', 'male', 'male', 'male',
       'female', 'female', 'male', 'female', 'female', 'male', 'female',
       'male', 'female', 'female', 'female', 'male', 'male', 'male',
       'female', 'female', 'female', 'male', 'female', 'male', 'male',
       'female', 'female', 'female', 'female', 'male', 'female', 'male',
       'female', 'female', 'female', 'female', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'male', 'female', 'male', 'male', 'male', 'male', 'other', 'male',
       'female', 'male', 'female', 'male', 'other', 'male', 'male', 'male',
       'female', 'male', 'female', 'female', 'female', 'female', 'male',
       'male', 'female', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'other', 'male', 'female', '', 'female', 'female',
       'female', 'male', 'female', 'female'],
      dtype='<U6')

In [255]:
import pandas as pd

In [256]:
df2 = pd.DataFrame({
        'name':name_array,
        'gender':gender_array,
        'career_stage':career_stage_array,
        'country':country_array,
        'subfield':subfield_array,
        'first_time':first_time_array
        })

df2

,career_stage,country,first_time,gender,name,subfield
0,,non-OECD,first_time,female,Julia Labay,exoplanets
1,senior-faculty,OECD,,female,Antonio Dorsey,solar
2,junior-faculty,OECD,returning,male,Rocco Mitchell,solar
3,senior-faculty,OECD,returning,male,Jessie Morlan,cosmology
4,,OECD,first_time,female,Kimberly Ellinger,cosmology
5,junior-faculty,non-OECD,returning,female,Shelly Mathews,exoplanets
6,grad-student,non-OECD,first_time,other,Victoria Lary,exoplanets
7,senior-faculty,non-OECD,first_time,male,Jeremy Santos,exoplanets
8,senior-faculty,non-OECD,returning,female,Karen Loynes,solar
9,senior-faculty,OECD,returning,female,Madelyn Skinner,astrophysics
10,grad-student,non-OECD,returning,female,Gabrielle Hayes,astrophysics
11,senior-faculty,OECD,returning,female,Patricia London,exoplanets
12,junior-faculty,,first_time,male,Mark Rochat,solar
13,junior-faculty,OECD,returning,male,Jared Torgersen,solar
14,grad-student,,first_time,female,Dorothea Padilla,exoplanets
15,grad-student,OECD,,male,Bradley Benson,
16,grad-student,OECD,returning,female,Jocelyn Comeau,astrophysics
17,senior-faculty,non-OECD,returning,female,Beverly Prevost,cosmology
18,senior-faculty,OECD,returning,female,Janet Wright,astrophysics
19,grad-student,non-OECD,first_time,male,George Randall,astrophysics
20,senior-faculty,non-OECD,returning,female,Heather Ball,solar
21,grad-student,non-OECD,first_time,female,Eva Oconnor,astrophysics
22,senior-faculty,OECD,first_time,male,Hollis Wells,exoplanets
23,senior-faculty,OECD,first_time,male,Matthew Coffey,
24,senior-faculty,non-OECD,first_time,female,Helen House,cosmology
25,senior-faculty,non-OECD,first_time,male,Charles Lail,astrophysics
26,senior-faculty,non-OECD,first_time,female,Cynthia Sloan,astrophysics
27,senior-faculty,non-OECD,first_time,male,Andrew Kirby,exoplanets
28,senior-faculty,non-OECD,returning,female,Nancy Bailey,astrophysics
29,junior-faculty,non-OECD,returning,male,Robert Alley,astrophysics
...,...,...,...,...,...,...
270,grad-student,OECD,returning,other,Matthew Isaacs,exoplanets
271,grad-student,OECD,first_time,male,Bobby Thomas,exoplanets
272,junior-faculty,OECD,returning,male,Pablo Solis,solar
273,junior-faculty,non-OECD,first_time,male,William Dougherty,astrophysics
274,senior-faculty,non-OECD,returning,female,Elsie North,solar
275,junior-faculty,OECD,first_time,male,Dale Arpin,astrophysics
276,senior-faculty,non-OECD,returning,female,Arline Ericson,astrophysics
277,grad-student,OECD,returning,female,Alpha Lane,cosmology
278,grad-student,OECD,first_time,female,Tracy Morris,cosmology
279,grad-student,non-OECD,first_time,female,Antoinette Cho,cosmology
280,junior-faculty,non-OECD,returning,male,Bradley Gutierrez,exoplanets
281,junior-faculty,non-OECD,first_time,male,Mark Woolfrey,exoplanets
282,senior-faculty,non-OECD,first_time,female,Karen Kisner,solar
283,senior-faculty,OECD,returning,female,Mary Aversano,astrophysics
284,junior-faculty,non-OECD,first_time,male,Joseph Wagner,astrophysics
285,grad-student,OECD,returning,male,Richard Wolfe,astrophysics
286,senior-faculty,OECD,first_time,female,Barabara Cain,solar
287,senior-faculty,OECD,first_time,male,Robert Burdette,cosmology
288,senior-faculty,non-OECD,first_time,male,Christopher Paget,cosmology
289,senior-faculty,non-OECD,first_time,male,Gary Mccaslin,solar
290,senior-faculty,non-OECD,first_time,other,Bob Mason,cosmology
291,junior-faculty,non-OECD,first_time,male,Dennis Bartlett,cosmology
292,senior-faculty,OECD,first_time,female,Betty Ippolito,exoplanets
293,grad-student,OECD,first_time,,Patrick Hutchens,cosmology
294,junior-faculty,OECD,first_time,female,Mary Davis,cosmology
295,grad-student,non-OECD,first_time,female,Loretta Birchfield,exoplanets
296,junior-faculty,OECD,first_time,female,Lakisha Davis,solar
297,senior-faculty,OECD,returning,male,Eugene Burke,exoplanets
298,grad-student,non-OECD,returning,female,Tanisha Paul,exoplanets
299,junior-faculty,non-OECD,returning,female,Ashley Libel,cosmology

In [257]:
df2.to_csv('datasets/all-even-300.csv',index=False)